
package wordlegame;

import java.awt.Label;
import javax.swing.JButton;
import javax.swing.JTextField;

public class WordleView extends javax.swing.JFrame {


    public WordleView() {
        initComponents();
    } //Creates new form WordleView

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        Q = new javax.swing.JButton();
        W = new javax.swing.JButton();
        E = new javax.swing.JButton();
        R = new javax.swing.JButton();
        T = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        U = new javax.swing.JButton();
        I = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        A = new javax.swing.JButton();
        S = new javax.swing.JButton();
        F = new javax.swing.JButton();
        D = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        X = new javax.swing.JButton();
        C = new javax.swing.JButton();
        V = new javax.swing.JButton();
        B = new javax.swing.JButton();
        N = new javax.swing.JButton();
        M = new javax.swing.JButton();
        Enter = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        label31 = new java.awt.Label();
        label30 = new java.awt.Label();
        label34 = new java.awt.Label();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label41 = new java.awt.Label();
        label40 = new java.awt.Label();
        label44 = new java.awt.Label();
        label42 = new java.awt.Label();
        label43 = new java.awt.Label();
        label51 = new java.awt.Label();
        label50 = new java.awt.Label();
        label54 = new java.awt.Label();
        label52 = new java.awt.Label();
        label53 = new java.awt.Label();
        label01 = new java.awt.Label();
        label00 = new java.awt.Label();
        label04 = new java.awt.Label();
        label02 = new java.awt.Label();
        label03 = new java.awt.Label();
        label11 = new java.awt.Label();
        label10 = new java.awt.Label();
        label14 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label21 = new java.awt.Label();
        label20 = new java.awt.Label();
        label24 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 102, 0));
        label1.setText("Wordle Game");

        Q.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Q.setText("Q");

        W.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        W.setText("W");

        E.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        E.setText("E");

        R.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        R.setText("R");

        T.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        T.setText("T");

        Y.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Y.setText("Y");

        U.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        U.setText("U");

        I.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        I.setText("I");

        O.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        O.setText("O");

        P.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        P.setText("P");

        A.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        A.setText("A");

        S.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        S.setText("S");

        F.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F.setText("F");

        D.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        D.setText("D");

        G.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        G.setText("G");

        H.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        H.setText("H");

        J.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        J.setText("J");

        K.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        K.setText("K");

        L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L.setText("L");

        Z.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Z.setText("Z");

        X.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        X.setText("X");

        C.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        C.setText("C");

        V.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        V.setText("V");

        B.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        B.setText("B");

        N.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        N.setText("N");

        M.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        M.setText("M");

        Enter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Enter.setText("ENTER");

        Clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Clear.setText("<--");

        label31.setAlignment(java.awt.Label.CENTER);
        label31.setBackground(new java.awt.Color(204, 204, 204));
        label31.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label30.setAlignment(java.awt.Label.CENTER);
        label30.setBackground(new java.awt.Color(204, 204, 204));
        label30.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label34.setAlignment(java.awt.Label.CENTER);
        label34.setBackground(new java.awt.Color(204, 204, 204));
        label34.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label32.setAlignment(java.awt.Label.CENTER);
        label32.setBackground(new java.awt.Color(204, 204, 204));
        label32.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label33.setAlignment(java.awt.Label.CENTER);
        label33.setBackground(new java.awt.Color(204, 204, 204));
        label33.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label41.setAlignment(java.awt.Label.CENTER);
        label41.setBackground(new java.awt.Color(204, 204, 204));
        label41.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label40.setAlignment(java.awt.Label.CENTER);
        label40.setBackground(new java.awt.Color(204, 204, 204));
        label40.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label44.setAlignment(java.awt.Label.CENTER);
        label44.setBackground(new java.awt.Color(204, 204, 204));
        label44.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label42.setAlignment(java.awt.Label.CENTER);
        label42.setBackground(new java.awt.Color(204, 204, 204));
        label42.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label43.setAlignment(java.awt.Label.CENTER);
        label43.setBackground(new java.awt.Color(204, 204, 204));
        label43.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label51.setAlignment(java.awt.Label.CENTER);
        label51.setBackground(new java.awt.Color(204, 204, 204));
        label51.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label50.setAlignment(java.awt.Label.CENTER);
        label50.setBackground(new java.awt.Color(204, 204, 204));
        label50.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label54.setAlignment(java.awt.Label.CENTER);
        label54.setBackground(new java.awt.Color(204, 204, 204));
        label54.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label52.setAlignment(java.awt.Label.CENTER);
        label52.setBackground(new java.awt.Color(204, 204, 204));
        label52.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label53.setAlignment(java.awt.Label.CENTER);
        label53.setBackground(new java.awt.Color(204, 204, 204));
        label53.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label01.setAlignment(java.awt.Label.CENTER);
        label01.setBackground(new java.awt.Color(204, 204, 204));
        label01.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label00.setAlignment(java.awt.Label.CENTER);
        label00.setBackground(new java.awt.Color(204, 204, 204));
        label00.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label04.setAlignment(java.awt.Label.CENTER);
        label04.setBackground(new java.awt.Color(204, 204, 204));
        label04.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label02.setAlignment(java.awt.Label.CENTER);
        label02.setBackground(new java.awt.Color(204, 204, 204));
        label02.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label03.setAlignment(java.awt.Label.CENTER);
        label03.setBackground(new java.awt.Color(204, 204, 204));
        label03.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setBackground(new java.awt.Color(204, 204, 204));
        label11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(204, 204, 204));
        label10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setBackground(new java.awt.Color(204, 204, 204));
        label14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setBackground(new java.awt.Color(204, 204, 204));
        label12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setBackground(new java.awt.Color(204, 204, 204));
        label13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label21.setAlignment(java.awt.Label.CENTER);
        label21.setBackground(new java.awt.Color(204, 204, 204));
        label21.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label20.setAlignment(java.awt.Label.CENTER);
        label20.setBackground(new java.awt.Color(204, 204, 204));
        label20.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label24.setAlignment(java.awt.Label.CENTER);
        label24.setBackground(new java.awt.Color(204, 204, 204));
        label24.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label22.setAlignment(java.awt.Label.CENTER);
        label22.setBackground(new java.awt.Color(204, 204, 204));
        label22.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        label23.setAlignment(java.awt.Label.CENTER);
        label23.setBackground(new java.awt.Color(204, 204, 204));
        label23.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Z, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(454, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(label04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label04, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Z, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        label31.getAccessibleContext().setAccessibleName("");
        label30.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordleView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton Clear;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton Enter;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private java.awt.Label label00;
    private java.awt.Label label01;
    private java.awt.Label label02;
    private java.awt.Label label03;
    private java.awt.Label label04;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label50;
    private java.awt.Label label51;
    private java.awt.Label label52;
    private java.awt.Label label53;
    private java.awt.Label label54;
    // End of variables declaration//GEN-END:variables
    //getter to return all the keyboard buttons on base of character.
    public JButton getAlpha(char c) {
        if(c=='a'||c=='A')
            return A;
        if(c=='b'||c=='B')
            return B;
        if(c=='c'||c=='C')
            return C;
        if(c=='d'||c=='D')
            return D;
        if(c=='e'||c=='E')
            return E;
        if(c=='f'||c=='F')
            return F;
        if(c=='g'||c=='G')
            return G;
        if(c=='h'||c=='H')
            return H;
        if(c=='i'||c=='I')
            return I;
        if(c=='j'||c=='J')
            return J;
        if(c=='k'||c=='K')
            return K;
        if(c=='l'||c=='L')
            return L;
        if(c=='m'||c=='M')
            return M;
        if(c=='n'||c=='N')
            return N;
        if(c=='o'||c=='O')
            return O;
        if(c=='p'||c=='P')
            return P;
        if(c=='q'||c=='Q')
            return Q;
        if(c=='r'||c=='R')
            return R;
        if(c=='s'||c=='S')
            return S;
        if(c=='t'||c=='T')
            return T;
        if(c=='u'||c=='U')
            return U;
        if(c=='v'||c=='V')
            return V;
        if(c=='w'||c=='W')
            return W;
        if(c=='x'||c=='X')
            return X;
        if(c=='y'||c=='Y')
            return Y;
        if(c=='z'||c=='Z')
            return Z;
        else
            return null;
    }

    public JButton getClear() {
        return Clear;
    }

    public JButton getEnter() {
        return Enter;
    }
    //getter to return all the board labels on base of index
    public Label getLabel(int row,int col) {
        if(row==0&&col==0)
            return label00;
        else if(row==0&&col==1)
            return label01;
        else if(row==0&&col==2)
            return label02;
        else if(row==0&&col==3)
            return label03;
        else if(row==0&&col==4)
            return label04;
        else if(row==1&&col==0)
            return label10;
        else if(row==1&&col==1)
            return label11;
        else if(row==1&&col==2)
            return label12;
        else if(row==1&&col==3)
            return label13;
        else if(row==1&&col==4)
            return label14;
        else if(row==2&&col==0)
            return label20;
        else if(row==2&&col==1)
            return label21;
        else if(row==2&&col==2)
            return label22;
        else if(row==2&&col==3)
            return label23;
        else if(row==2&&col==4)
            return label24;
        else if(row==3&&col==0)
            return label30;
        else if(row==3&&col==1)
            return label31;
        else if(row==3&&col==2)
            return label32;
        else if(row==3&&col==3)
            return label33;
        else if(row==3&&col==4)
            return label34;
        else if(row==4&&col==0)
            return label40;
        else if(row==4&&col==1)
            return label41;
        else if(row==4&&col==2)
            return label42;
        else if(row==4&&col==3)
            return label43;
        else if(row==4&&col==4)
            return label44;
        else if(row==5&&col==0)
            return label50;
        else if(row==5&&col==1)
            return label51;
        else if(row==5&&col==2)
            return label52;
        else if(row==5&&col==3)
            return label53;
        else if(row==5&&col==4)
            return label54;
        else
            return null;
    }
}
